bump:
  stable tag: readme.txt
  version: logger.php
dest:
  lang: languages/
language:
  domain: logger
  team: Gemini Labs <support@geminilabs.io>
  translator: Paul Ryley <paul@geminilabs.io>
watch:
  php:
    - plugin/**/*.php
    - views/**/*.php
    - '*.php'
